### PR TITLE
Fix NumberFormatException when query parameters are missing

### PR DESCRIPTION
**Pull request by rockerhieu**
More details: https://github.com/hoko/hoko-android/issues/15

### CODE REVIEW

**Comment by rockerhieu** [comment]
I was going to fix the failing test case, but then realized this comment `// For CI to work for the time being, this definitely needs fixing (is only breaking on travis and not locally)`

**Comment by rikas** [comment]
Thanks @rockerhieu!

@pedrovieira7 can you look at it?

**Comment by pedrovieira** [comment]
Thank you @rockerhieu, merged! 💪

**Comment by rockerhieu** [comment]
@pedrovieira7 cool bean! Any idea the fix will be available on maven?

**Pull request merged**
